### ISSUE TITLE
New feature: S3 compatible driver

### ISSUE THREAD

**Issue by fernandodelaiglesia** [SynchroLabs/StashBox#1]
Dear friends at SynchroLabs,

I find Stashbox very useful for configuration file (and other) distribution in a Docker microservices environment, but I miss a S3 compatible storage driver. So that I created such a driver based on minio-js. I would like to contribute this driver to StashBox if it is OK for you (but I need the corresponding permisions to push a new branch and ask for a pull request).

I hope this can be interesting for you

Thank you very much in advance

Best

PS: I'm sorry to use an Issue creation for this but I was unable to contact you in other way

**Comment by BobDickinson** [comment]
Does this provide any additional functionality to the S3 support that is already provided by StashBox via PkgCloud?

**Comment by fernandodelaiglesia** [comment]
Hi Bob,

Thank you for your answer

As far as I could view, current PkgCloud does not support non-Amazon S3 compatible service (as for example Atmos from DellEMC, Swarm from Caringo or OBS form Telefonica Open Cloud).  When configuring the mount with PkgCloud I don't see how to configure a custom endpoint (you can select just the region, that points to Amazon endpoints). And this is the additional functionality: support to non Amazon, S3 compatible services.

Thanks
Best

Fernando

**Comment by BobDickinson** [comment]
It seems that pkgcloud may support non-Amazon endpoints.  See: https://github.com/pkgcloud/pkgcloud/blob/b7d7218d1d1c7f9f81905f03103855ead3eb277c/lib/pkgcloud/amazon/client.js#L47-L49

It looks like you can just set "endpoint".  You might try and see if that works for you.

That being said, I have no objection to you adding your driver.

**Comment by BobDickinson** [comment]
You should be able to submit a pull request without being added as a contributor.

**Comment by fernandodelaiglesia** [comment]
I tried to add the endpoint to the config file and it seems to point to the custom endpoint I set, but after a lot of tests I alwais get a "NoSuchKey" error

[2017-04-22 16:56:14.078] [ERROR] console - NoSuchKey: The specified key does not exist.

(of course the objet is there, I clould use it with the "alternative" s3 driver I created).

Here is the config file I used

{
  "mounts":
     [
       {
	       "mount": "/",
		   "provider": "amazon",
		   "basePath": "fimtest", <---- the bucket where I stored the file I request
		   "keyId": "TheAccesskey",
		   "key": "TheSecretKey",
		   "region": "eu-west-2",
		   "endpoint": "obs.na-mexico-1.telefonicaopencloud.com"
       }
     ]
}

As for the submision of the s3 copatible driver, when I try to puth the branch I created for that I get an access denied

$ git push -u origin s3compatible_driver
remote: Permission to SynchroLabs/StashBox.git denied to fernandodelaiglesia.
fatal: unable to access 'https://github.com/SynchroLabs/StashBox.git/': The requested URL returned error: 403

Thank you
Best

**Comment by BobDickinson** [comment]
You don't have permissions to push your changes to the repo.  You should create a pull request.  This will allow me to review your changes and merge them.  See: https://help.github.com/articles/creating-a-pull-request/

It is common on an open source project to make your first contributions as pull requests, and at some point the maintainers trust you enough based on your PRs to add you as a maintainer.

**Comment by fernandodelaiglesia** [comment]
I'm sorry, it's the first time I try to submmit code to a repo that is not mine. I just did the pull request. I hope all is OK.

Thank you

**Comment by fernandodelaiglesia** [comment]
Hi Bob,

Did you have the opportunity to review the proposed changes?

Thank you
Best

**Comment by fernandodelaiglesia** [comment]
Solved with merge https://github.com/SynchroLabs/StashBox/pull/2
Thank you Bob
Best
